apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanobot-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nanobot-frontend
  template:
    metadata:
      labels:
        app: nanobot-frontend
    spec:
      containers:
      - name: nanobot-frontend
        image: 411307820369.dkr.ecr.us-east-1.amazonaws.com/nanobot-frontend:1.7
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          value: "http://a7f784e35db984efbbb175fb2dc129c0-486246873.us-east-1.elb.amazonaws.com"
